---
# tasks file for telegraf-simple
- name: add influxdata repository
  yum_repository:
    name: influxdata
    description: "InfluxData Repository - {{ ansible_distribution }} $releasever"
    baseurl: "https://repos.influxdata.com/{{ ansible_distribution | lower }}/$releasever/$basearch/stable"
    gpgcheck:  yes
    gpgkey: "https://repos.influxdata.com/influxdb.key"
  environment: proxy_environment
  ignore_errors: yes

- name: install telegraf
  yum:
    name: telegraf
    state: present
  environment: proxy_environment
  notify: restart telegraf
  ignore_errors: yes

- name: configure telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf
  ignore_errors: yes

- name: start telegraf
  service:
    name: telegraf
    state: started
    enabled: yes
  ignore_errors: yes
